testing_mode = true
payment_provider = "stripe"
stripe_api_key_test = "rk_test_51OSkOTLkmlsZnSONmLVZOBpOzD1iUb8BFRv0Fg36kGiPYWIBSNvoIG0q9GdRwixqovjD4PROFAfzLWvXpbrKoEwp00DYToKxIM" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://donate.stripe.com/test_8wM16N2af1vZ3FSbIL" #only needed if using Stripe
client_id = "590..."
client_secret = "GO..."
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://your_app_url..."
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee